### ISSUE TITLE
Please provide simple NonDet example

### ISSUE THREAD

**Issue by tomjaguarpaw** [sayo-hs/heftia#13]
I was expecting `example2` to work, but I can't get it to type check. `example1` works fine, so it's not a problem with doing `IO` specifically.

Could you please provide a simple example of using `NonDet`?

```.hs
-- See
-- https://github.com/sayo-hs/heftia/blob/08f5cfe6a8f5c0383ea2b02e93326552400f7fd3/heftia-effects/Example/Teletype/Main.hs
{-# LANGUAGE GHC2021 #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeFamilies #-}

import Control.Applicative ((<|>))
import Control.Effect.ExtensibleChurch (runEff)
import Control.Effect.Interpreter.Heftia.NonDet (runNonDet)
import Control.Monad.IO.Class (liftIO)

example1 :: IO ()
example1 =
  runEff $
    liftIO (putStrLn "Hello")

-- test28.hs:37:17: error:
--     • The effect class: Data.Effect.NonDet.ChooseH
--        was not found in the union:
--           '[]
--     • In a stmt of a 'do' block: r <- pure 1 <|> pure 2
--       In the second argument of ‘($)’, namely
--         ‘do r <- pure 1 <|> pure 2
--             liftIO (putStrLn "Hello")
--             pure r’
--       In the second argument of ‘($)’, namely
--         ‘runNonDet
--            $ do r <- pure 1 <|> pure 2
--                 liftIO (putStrLn "Hello")
--                 pure r’
--    |
-- 37 |     r <- pure 1 <|> pure 2
--    |                 ^^^
example2 :: IO [Int]
example2 = runEff $
  runNonDet $ do
    r <- pure 1 <|> pure 2
    liftIO (putStrLn "Hello")
    pure r
```

**Comment by ymdryo** [comment]
You need `runChooseH` before `runNonDet`.

```haskell
import Control.Effect.Interpreter.Heftia.NonDet (runChooseH)

example2 :: IO [Int]
example2 = runEff $
    runNonDet . runChooseH $ do
        r <- pure 1 <|> pure 2
        liftIO (putStrLn "Hello")
        pure r
```

There's an example in SemanticsZoo that might be helpful:
https://github.com/sayo-hs/heftia/blob/v0.3.1/heftia-effects/Example/SemanticsZoo/Main.hs#L66-L81

For NonDet, two versions are provided: a first-order version and a higher-order version. The first-order effect is called `Choose`, and the higher-order one is called `ChooseH`. `runNonDet` handles `Choose`, but to use `<|>`, you need `ChooseH`. `ChooseH` needs to be eventually transformed into `Choose` and then handled with `runChoose`, so `runChooseH` is required for that.
https://hackage.haskell.org/package/data-effects-0.1.2.0/docs/Data-Effect-NonDet.html#t:Choose
https://hackage.haskell.org/package/data-effects-0.1.2.0/docs/Data-Effect-NonDet.html#t:ChooseH
https://hackage.haskell.org/package/heftia-effects-0.3.1.0/docs/Control-Effect-Interpreter-Heftia-NonDet.html#v:runChoose
https://hackage.haskell.org/package/heftia-effects-0.3.1.0/docs/Control-Effect-Interpreter-Heftia-NonDet.html#v:runChooseH

This aspect is a bit different from other libraries.

**Comment by ymdryo** [comment]
Since it's not user-friendly, perhaps `runNonDet` should be renamed to `runChoose`, and we might redefine `runNonDet = runChoose . runChooseH`. I think we'll make this change in the next version.

**Comment by ymdryo** [comment]
The naming might be a bit confusing, so I'll change it if there are better interface ideas.

**Comment by tomjaguarpaw** [comment]
Thank you, that works!
