### ISSUE TITLE
Please provide simple bracket example

### ISSUE THREAD

**Issue by tomjaguarpaw** [sayo-hs/heftia#14]
I would like to understand how `bracket` works in heftia. I have got as far as the below, but I don't know how to run something that has a `SendSig Resource` in it. I feel this must require `resourceToIO`, but I don't see how I should use it. Can you help?

```.hs
{-# LANGUAGE GHC2021 #-}

import Control.Applicative ((<|>))
import Control.Effect.ExtensibleChurch (runEff)
import Control.Effect.Interpreter.Heftia.NonDet (runNonDet, runChooseH)
import Control.Monad.IO.Class (liftIO, MonadIO)
import Data.Effect.Resource (bracket_, Resource)
import Control.Effect (SendSig)

example :: (MonadIO f, SendSig Resource f) => f Integer
example =
    bracket_
        (liftIO (putStrLn "Acquired"))
        (liftIO (putStrLn "Released"))
        ( do
              r <- pure 1
              liftIO (putStrLn "Used")
              pure r
          )
```

**Comment by ymdryo** [comment]
Ah, sorry about that. `resourceToIO` hasn't been implemented yet. For now, an interface similar to `unliftio` can be used with [runUnliftIO](https://hackage.haskell.org/package/heftia-effects-0.3.1.0/docs/Control-Effect-Interpreter-Heftia-Unlift.html#v:runUnliftIO) and [withRunInBase](https://hackage.haskell.org/package/data-effects-0.1.1.0/candidate/docs/Data-Effect-Unlift.html#v:withRunInBase).

```haskell
import Control.Effect (type (<<:))
import Control.Effect.Interpreter.Heftia.Unlift (runUnliftIO)
import Control.Exception (bracket_)
import Control.Monad.Freer.Church (FreerChurch)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Data.Effect.Unlift (UnliftIO, withRunInIO)
import Data.Hefty.Extensible (ExtensibleUnion)

example :: (MonadIO f, UnliftIO <<: f) => f Integer -- `<<:` = `SendSig`
example =
    withRunInIO \run -> do
        bracket_
            (run $ liftIO (putStrLn "Acquired"))
            (run $ liftIO (putStrLn "Released"))
            ( run do
                r <- pure 1
                liftIO (putStrLn "Used")
                pure r
            )

main :: IO ()
main = do
    x <- runUnliftIO @FreerChurch @ExtensibleUnion example
    print x

```

I think it's possible to write `resourceToIO` using this method as well.

**Comment by ymdryo** [comment]
Since `UnliftIO` conflicts with continuation-based operations, you cannot use the usual `runState` or `runThrow` handlers; instead, you need to use *IO-based handlers* like [runStateIORef](https://hackage.haskell.org/package/heftia-effects-0.3.1.0/docs/Control-Effect-Interpreter-Heftia-State.html#v:runStateIORef) or [runThrowIO](https://hackage.haskell.org/package/heftia-effects-0.3.1.0/docs/Control-Effect-Interpreter-Heftia-Except.html#v:runThrowIO) in this case.

At present, the usability of the `UnliftIO` effect is not very good. Currently, only these two IO-based handlers are implemented. (Additionally, as of the latest version 0.3.1 on Hackage, the type signature of `runStateIORef` is incorrect and lacks sufficient generalization.) I need to expand them further.

**Comment by ymdryo** [comment]
Added [`runResourceIO`](https://hackage.haskell.org/package/heftia-effects-0.4.0.0/docs/Control-Monad-Hefty-Resource.html#v:runResourceIO) in version 0.4.  
Also added a usage example.  
https://github.com/sayo-hs/heftia/blob/develop/heftia-effects/Example/UnliftIO/Main.hs

Please feel free to reopen if there is anything.

**Comment by ymdryo** [comment]
@tomjaguarpaw

Perhaps you are attempting tests related to what is written in this article? [Bluefin streams finalize promptly](https://h2.jaguarpaw.co.uk/posts/bluefin-streams-finalize-promptly/)

If you would like, I can explain this to you.

**Comment by ymdryo** [comment]
OK. In Heftia, higher-order effects (like `Resource`) must be interpreted before `runNonDet` and `runCoroutine` to ensure semantics safety for *Non-Scoped Resumption*[^1] feature in algebraic effects. Bluefin likely avoids this limitation by not supporting Non-Scoped Resumption. As a result, functions like `bracket` cannot be used within `produce`/`consume` in Heftia and must be applied externally. https://github.com/sayo-hs/heftia/blob/99aa48ff7a8abbb18825b774fdf588eb98c12390/heftia-effects/Example/Stream/Main.hs

Bluefin seems to handle this aspect better than Heftia by focusing solely on IO-fused effects, allowing it to work effectively with less consideration. I think this is a another valid design philosophy. Nice 👍

[^1]: This feature allows continuations to be moved to another handler’s scope, enabling handler changes during control flow.

**Comment by ymdryo** [comment]
A new stream interpreter has been implemented using a mechanism similar to Bluefin.
https://github.com/sayo-hs/heftia/blob/v0.5.0/heftia-effects/Example/Stream/Main.hs
As a result, Heftia is now able to use `bracket` freely within streams.
