### ISSUE TITLE
Scoped ala polysemy

### ISSUE THREAD

**Issue by googleson78** [sayo-hs/heftia#17]
Hey! This project sounds really exciting!

I still haven't taken a deeper look, but does `heftia` currently support something like polysemy's `Scoped`?

https://hackage.haskell.org/package/polysemy-1.9.2.0/docs/Polysemy-Scoped.html

https://www.tweag.io/blog/2022-01-05-polysemy-scoped/

I think this is a *critically* important effect, as it represents some key things (e.g. DB transactions) at the type level, and I would love to know how it can be done in `heftia`.

**Comment by ymdryo** [comment]
Yes, it is experimental and not very well documented, but the `Scoped` effect (also known as the `Provider` effect in `effectful` terminology) is implemented. Here is some example code using it with the file system (or rather, more like a DB?):

https://github.com/sayo-hs/heftia/blob/v0.5.0/heftia-effects/Example/FileSystemProvider/Main.hs

The types are a bit complex and hard to understand, so I plan to improve this in a future version when I have time to dedicate to it.

**Comment by googleson78** [comment]
Awesome, thanks! Feel free to close if there's nothing else to discuss here. I probably won't have the time to try this out soon, but it's very nice to know that it's somewhat covered.
